# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: a307a2549e02
Revises: 4d157222c9eb
Create Date: 2020-04-30 02:50:44.587269

"""

# revision identifiers, used by Alembic.
revision = 'a307a2549e02'
down_revision = '4d157222c9eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folders_slug_key', 'folders', type_='unique')
    op.drop_column('folders', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('folders_slug_key', 'folders', ['slug'])
    # ### end Alembic commands ###
